
[2016-05-18 07:43:19] Traceback (most recent call last):

  File "task.pyx", line 55, in cefpython_py27.PyTaskRunnable (cefpython.cpp:29291)

  File "wms_gui.py", line 379, in _CreatePopup
    frame = MainFrame(url=url, popup=True)

NameError: global name 'MainFrame' is not defined


[2016-05-18 08:04:47] Traceback (most recent call last):

  File "wms_gui.py", line 667, in <module>
    app = WMS(False)

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 578, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 501, in __init__
    self.WMSLoad()

  File "wms_gui.py", line 519, in WMSLoad
    self.browser.ExecuteJavascript('alert("test");')

AttributeError: 'cefpython_py27.PyBrowser' object has no attribute 'ExecuteJavascript'


[2016-05-18 08:07:19] Traceback (most recent call last):

  File "wms_gui.py", line 667, in <module>
    app = WMS(False)

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 578, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 501, in __init__
    self.WMSLoad()

  File "wms_gui.py", line 519, in WMSLoad
    self.browser.ExecuteJavascript('alert("test");')

AttributeError: 'cefpython_py27.PyBrowser' object has no attribute 'ExecuteJavascript'


[2016-05-18 08:09:29] Traceback (most recent call last):

  File "wms_gui.py", line 667, in <module>
    app = WMS(False)

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 578, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 501, in __init__
    self.WMSLoad()

  File "wms_gui.py", line 519, in WMSLoad
    self.browser.ExecuteFunction('alert("test");')

AttributeError: 'cefpython_py27.PyBrowser' object has no attribute 'ExecuteFunction'


[2016-05-18 08:10:00] Traceback (most recent call last):

  File "wms_gui.py", line 667, in <module>
    app = WMS(False)

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 578, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 501, in __init__
    self.WMSLoad()

  File "wms_gui.py", line 519, in WMSLoad
    self.browser.ExecuteFunction("alert('test');")

AttributeError: 'cefpython_py27.PyBrowser' object has no attribute 'ExecuteFunction'


[2016-05-18 14:58:53] Traceback (most recent call last):

  File "wms_gui.py", line 667, in <module>
    app = WMS(False)

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 578, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 501, in __init__
    self.WMSLoad()

  File "wms_gui.py", line 519, in WMSLoad
    self.browser.ExecuteFunction("alert('test');")

AttributeError: 'cefpython_py27.PyBrowser' object has no attribute 'ExecuteFunction'


[2016-05-18 15:02:35] Traceback (most recent call last):

  File "wms_gui.py", line 667, in <module>
    app = WMS(False)

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 578, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 501, in __init__
    self.WMSLoad()

  File "wms_gui.py", line 519, in WMSLoad
    self.clientHandler.mainBrowser.ExecuteFunction("alert('test');")

AttributeError: 'cefpython_py27.PyBrowser' object has no attribute 'ExecuteFunction'


[2016-05-18 15:05:02] Traceback (most recent call last):

  File "wms_gui.py", line 677, in <module>
    app = WMS(False)

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 588, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 501, in __init__
    self.WMSLoad()

  File "wms_gui.py", line 540, in WMSLoad
    for filename in fnmatch.filter(filenames, '*.json'):

NameError: global name 'fnmatch' is not defined


[2016-05-18 15:08:14] Traceback (most recent call last):

  File "wms_gui.py", line 677, in <module>
    app = WMS(False)

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 588, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 501, in __init__
    self.WMSLoad()

  File "wms_gui.py", line 527, in WMSLoad
    self.browser.SetJavascriptBindings(jsBindings)

NameError: global name 'jsBindings' is not defined


[2016-05-18 15:11:53] Traceback (most recent call last):

  File "wms_gui.py", line 677, in <module>
    app = WMS(False)

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 588, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 501, in __init__
    self.WMSLoad()

  File "wms_gui.py", line 519, in WMSLoad
    self.browser.SetProperty("test", "testabc")

AttributeError: 'cefpython_py27.PyBrowser' object has no attribute 'SetProperty'


[2016-05-18 15:14:38] Traceback (most recent call last):

  File "wms_gui.py", line 679, in <module>
    app = WMS(False)

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 590, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 503, in __init__
    self.WMSLoad()

  File "wms_gui.py", line 521, in WMSLoad
    self.browserFrame.SetProperty("test", "testabc")

AttributeError: 'cefpython_py27.PyFrame' object has no attribute 'SetProperty'


[2016-05-18 15:32:02] Traceback (most recent call last):

  File "wms_gui.py", line 681, in <module>
    app = WMS(False)

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 592, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 549, in __init__
    self.browser.current_page = 'loading'

AttributeError: 'cefpython_py27.PyBrowser' object has no attribute 'current_page'


[2016-05-18 15:32:20] Traceback (most recent call last):

  File "wms_gui.py", line 681, in <module>
    app = WMS(False)

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 592, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 549, in __init__
    self.browser.current_page = 'loading'

AttributeError: 'cefpython_py27.PyBrowser' object has no attribute 'current_page'


[2016-05-18 15:35:26] Traceback (most recent call last):

  File "wms_gui.py", line 680, in <module>
    app = WMS(False)

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 591, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 551, in __init__
    self.browser.SetClientHandler(self.clientHandler)

  File "browser.pyx", line 267, in cefpython_py27.PyBrowser.SetClientHandler (cefpython.cpp:11035)

  File "browser.pyx", line 280, in cefpython_py27.PyBrowser.SetClientHandler (cefpython.cpp:10978)

  File "browser.pyx", line 177, in cefpython_py27.PyBrowser.SetClientCallback (cefpython.cpp:9684)

  File "browser.pyx", line 263, in cefpython_py27.PyBrowser.SetClientCallback_CEF3 (cefpython.cpp:10613)

Exception: Browser.SetClientCallback() failed: unknown callback: WMSLoad


[2016-05-18 15:41:57] Traceback (most recent call last):

  File "wms_gui.py", line 745, in <module>
    app = WMS(False)

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 656, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 604, in __init__
    cefpython.SetGlobalClientCallback("OnLoadEnd", self.OnLoadEnd)

  File "cefpython.pyx", line 483, in cefpython_py27.SetGlobalClientCallback (cefpython.cpp:78597)

  File "cefpython.pyx", line 488, in cefpython_py27.SetGlobalClientCallback (cefpython.cpp:78503)

Exception: SetGlobalClientCallback() failed: invalid callback name = OnLoadEnd

                                                                                                                                                                                                                                                                                                                                                                                        \_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 592, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 549, in __init__
    self.browser.current_page = 'loading'

AttributeError: 'cefpython_py27.PyBrowser' object has no attribute 'current_page'


[2016-05-18 15:35:26] Traceback (most recent call last):

  File "w\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 592, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 549, in __init__
    self.browser.current_page = 'loading'

AttributeError: 'cefpytho\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 592, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 549, in __init__
    self.browser.current_page = 'loading'

AttributeError: 'cefpython_py27.PyBrowser' object has no attribute 'current_page'


[2016-05-18 15:35:26] Traceback (most recent call la\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 592, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 549, in __init__
    self.browser.current_page = 'loading'

AttributeError: 'cefpython_py27.PyBrowser' object has no attribute 'current_page'


[2016-05-18 15:35:26] Traceback \_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 592, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 549, in __init__
    self.browser.current_page = 'loading'

AttributeError: 'cefpython_py27.PyBrowser' object has no attribute 'current_page'


[2016-05-18 15:35:26] Traceback (most recent call last):

  File "wms_gui.py", line 680, in <module>
    app = WMS(False)

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 591, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 551, in __init__
    self.browser.SetClientHandler(self.clientHandler)

  File "browser.pyx", line 267, in cefpython_py27.PyBrowser.SetClientHandler (cefpython.cpp:11035)

  File "browser.pyx", line 280, in cefpython_py27.PyBrowser.SetClientHandler (cefpython.cpp:10978)

  File "browser.pyx", line 177, in cefpython_py27.PyBrowser.SetClientCallback (cefpython.cpp:9684)

  File "browser.pyx", line 263, in cefpython_py27.PyBrowser.SetClientCallback_CEF3 (cefpython.cpp:10613)

Exception: Browser.SetClientCallback() failed: unknown callback: WMSLoad


[2016-05-18 15:41:57] Traceback (most recent call last):

  File "wms_gui.py", line 745, in <module>
    app = WMS(False)

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8628, in __init__
    self._BootstrapApp()

  File "c:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 656, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 604, in __init__
    cefpython.SetGlobalClientCallback("OnLoadEnd", self.OnLoadEnd)

  File "cefpython.pyx", line 483, in cefpython_py27.SetGlobalClientCallback (cefpython.cpp:78597)

  File "cefpython.pyx", line 488, in cefpython_py27.SetGlobalClientCallback (cefpython.cpp:78503)

Exception: SetGlobalClientCallback() failed: invalid callback name = OnLoadEnd

                                                                                                                                                                                                                                                                                                                                                                                        \_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 592, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 549, in __init__
    self.browser.current_page = 'loading'

AttributeError: 'cefpython_py27.PyBrowser' object has no attribute 'current_page'


[2016-05-18 15:35:26] Traceback (most recent call last):

  File "w\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 592, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 549, in __init__
    self.browser.current_page = 'loading'

AttributeError: 'cefpytho\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 592, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 549, in __init__
    self.browser.current_page = 'loading'

AttributeError: 'cefpython_py27.PyBrowser' object has no attribute 'current_page'


[2016-05-18 15:35:26] Traceback (most recent call la
[2016-05-18 16:01:23] Traceback (most recent call last):

  File "load_handler_cef3.pyx", line 52, in cefpython_py27.LoadHandler_OnLoadEnd (cefpython.cpp:60218)

  File "wms_gui.py", line 589, in OnLoadEnd
    self.WMSLoad()

  File "wms_gui.py", line 627, in WMSLoad
    for filename in fnmatch.filter(filenames, '*.json'):

NameError: global name 'fnmatch' is not defined

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              6, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 592, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 549, in __init__
    self.browser.current_page = 'loading'

AttributeError: 'cefpython_py27.PyBrowser' object has no attribute 'current_page'


[2016-05-18 15:35:26] Traceback (most recent call last):

  File "wms_gui.py", line 680, in <module>
    app = WMS(False                                                                                                                                                                                                                                                                                                                                                                                                                                      
[2016
[2016-05-22 11:23:24] Traceback (most recent call last):

  File "load_handler_cef3.pyx", line 52, in cefpython_py27.LoadHandler_OnLoadEnd (cefpython.cpp:60218)

  File "wms_gui.py", line 616, in OnLoadEnd
    self.WMSLoad()

  File "wms_gui.py", line 694, in WMSLoad
    self.WMSCoreListLocalFiles()

  File "wms_gui.py", line 713, in WMSCoreListLocalFiles
    self.browser.GetMainFrame().ExecuteFunction("updateLocalFileTree('"+str(json.dump(jsTreeData))+"')")

TypeError: dump() takes at least 2 arguments (1 given)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                6, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)

  File "wms_gui.py", line 592, in OnInit
    self.mainFrame = WMSMainFrame()

  File "wms_gui.py", line 549, in __init__
    self.browser.current_page = 'loading'

AttributeError: 'cefpython_py27.PyBrowser' object has no attribute 'current_page'


[2016-05-18 15:35:26] Traceback (most recent call last):

  File "wms_gui.py", line 680, in <module>
    app = WMS(False                                                                                                                                                                                                                                                                                                                                                                                                                                      
[2016
[2016-05-22 11:23:24] Traceback (most recent call last):

  File "load_handler_cef3.pyx", line 52, in cefpython_py27.LoadHandler_OnLoadEnd (cefpython.cpp:60218)

  File "wms_gui.py", line 616, in OnLoadEnd
    self.WMSLoad()

  File "wms_gui.py", line 694, in WMSLoad
    self.WMSCoreListLocalFiles()

  File "wms_gui.py", line 713, in WMSCoreListLocalFiles
    self.browser.GetMainFrame().ExecuteFunction("updateLocalFileTree('"+str(json.dump(jsTreeData))+"')")

TypeError: dump() takes at least 2 arguments (1 given)

                                                                                                                                                                                                                                                                                                                                              
[2016-05-22 11:59:35] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "wms_gui.py", line 743, in WMSCoreNavigate
    self.browser.LoadUrl(url)

AttributeError: 'NoneType' object has no attribute 'LoadUrl'

                                                                                                                                                                                                                                                                                                                                                                WMSCoreListLocalFiles
    self.browser.GetMainFrame().ExecuteFunction("updateLocalFileTree('"+str(json.dump(jsTreeData))+"')")

TypeError: dump() takes at least 2 arguments (1 given)

                                                                                                                                                               
[2016-05-22 12:08:23] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "wms_gui.py", line 738, in WMSCoreListLocalFiles
    self.browser.GetMainFrame().ExecuteFunction("updateLocalFileTree('"+str(json.dumps(jsTreeData))+"')")

  File "c:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)

  File "c:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)

  File "c:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)

UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 6: invalid continuation byte

                                                                                                                                                                                                                                                                                                                                                                     WMSCoreListLocalFiles
    self.browser.GetMainFrame().ExecuteFunction("updateLocalFileTree('"+str(json.dump(jsTreeData))+"')")

TypeError: dump() takes at least 2 arguments (1 given)

                                                                                                                                                                             WMSCoreListLocalFiles
    self.browser.GetMainFrame().ExecuteFunction("updateLocalFileTree('"+str(json.dump(jsTreeData))+"')")

TypeError: dump() takes at least 2 arguments (1 given)

                                                                                                                                                                             WMSCoreListLocalFiles
    self.browser.GetMainFrame().ExecuteFunction("updateLocalFileTree('"+str(json.dump(jsTreeData))+"')")

TypeError: dump() takes at least 2 arguments (1 given)

                                                                                                                                                                             WMSCoreListLocalFiles
    self.browser.GetMainFrame().ExecuteFunction("updateLocalFileTree('"+str(json.dump(jsTreeData))+"')")

TypeError: dump() takes at least 2 arguments (1 given)

                                                                                                                                        WMSCoreListLocalFiles
    self.browser.GetMainFrame().ExecuteFunction("updateLocalFileTree('"+str(json.dump(jsTreeData))+"')")

TypeError: dump() takes at least 2 arguments (1 given)

                                                                                                                                                                                                                                                                                                                                              
[2016-05-22 11:59:35] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "wms_gui.py", line 743, in WMSCoreNavigate
    self.browser.LoadUrl(url)

AttributeError: 'NoneType' object has no attribute 'LoadUrl'

                                                                                                                                                                                                                                                                                                                                                                WMSCoreListLocalFiles
    self.browser.GetMainFrame().ExecuteFunction("updateLocalFileTree('"+str(json.dump(jsTreeData))+"')")

TypeError: dump() takes at least 2 arguments (1 given)

                                                                                                                                                               
[2016-05-22 12:08:23] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "wms_gui.py", line 738, in WMSCoreListLocalFiles
    self.browser.GetMainFrame().ExecuteFunction("updateLocalFileTree('"+str(json.dumps(jsTreeData))+"')")

  File "c:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)

  File "c:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)

  File "c:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)

UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 6: invalid continuation byte

                                                                                                                                                                                                                                                                                                                                                                     WMSCoreListLocalFiles
    self.browser.GetMainFrame().ExecuteFunction("updateLocalFileTree('"+str(json.dump(jsTreeData))+"')")

TypeError: dump() takes at least 2 arguments (1 given)

                                                                                                                                                                             WMSCoreListLocalFiles
    self.browser.GetMainFrame().ExecuteFunction("updateLocalFileTree('"+str(json.dump(jsTreeData))+"')")

TypeError: dump() takes at least 2 arguments (1 given)

                                                                                                                                                                             WMSCoreListLocalFiles
    self.browser.GetMainFrame().ExecuteFunction("updateLocalFileTree('"+str(json.dump(jsTreeData))+"')")

TypeError: dump() takes at least 2 arguments (1 given)

                                                                                                                                                                             
[2016-05-22 12:37:28] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "wms_gui.py", line 736, in WMSCoreListLocalFiles
    print "===============:"+index

TypeError: cannot concatenate 'str' and 'int' objects

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
[2016-05-22 16:58:38] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "wms_gui.py", line 772, in WMSCoreListLocalFiles
    currentFolderObject["children"] = buildChildrens((index + 1), pathFolders)

  File "wms_gui.py", line 750, in buildChildrens
    currentFolderObject["children"] = buildChildrens((index + 1), pathFolders)

  File "wms_gui.py", line 738, in buildChildrens
    dirs = os.listdir(currentPathFolder)

WindowsError: [Error 3] Le chemin d�acc�s sp�cifi� est introuvable: 'C:\\Program Files7-Zip/*.*'

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
[2016-05-22 17:10:58] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "wms_gui.py", line 797, in WMSCoreListLocalFiles
    self.browser.GetMainFrame().ExecuteFunction("updateLocalFileTree('"+str(json.dumps(jsTreeData))+"')")

  File "c:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)

  File "c:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)

  File "c:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)

UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 6: invalid continuation byte


[2016-05-22 17:11:33] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "wms_gui.py", line 797, in WMSCoreListLocalFiles
    self.browser.GetMainFrame().ExecuteFunction("updateLocalFileTree('"+str(json.dumps(jsTreeData))+"')")

  File "c:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)

  File "c:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)

  File "c:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)

UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 6: invalid continuation byte

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
[2016-05-22 17:14:56] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "wms_gui.py", line 797, in WMSCoreListLocalFiles
    self.browser.GetMainFrame().ExecuteFunction("updateLocalFileTree('"+str(json.dumps(jsTreeData))+"')")

  File "c:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)

  File "c:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)

  File "c:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)

UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 6: invalid continuation byte

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              utf8' codec can't decode byte 0xe9 in position 6: invalid continuation byte


[2016-05-22 17:17:06] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "wms_gui.py", line 775, in WMSCoreListLocalFiles
    currentFolderObject["children"] = buildChildrens((index + 1), pathFolders)

  File "wms_gui.py", line 742, in buildChildrens
    'text': file.encode('latin-1'),

Unutf8' codec can't decode byte 0xe9 in position 6: invalid continuation byte

                                                                                                                                                                                                                                                                                                                                                                                                             utf8' codec can't decode byte 0xe9 in position 6: invalid continuation byte

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              utf8' codec can't decode byte 0xe9 in position 6: invalid continuation byte


[2016-05-22 17:17:06] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "wms_gui.py", line 775, in WMSCoreListLocalFiles
    currentFolderObject["children"] = buildChildrens((index + 1), pathFolders)

  File "wms_gui.py", line 742, in buildChildrens
    'text': file.encode('latin-1'),

Un
[2016-05-22 17:18:47] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "wms_gui.py", line 775, in WMSCoreListLocalFiles
    currentFolderObject["children"] = buildChildrens((index + 1), pathFolders)

  File "wms_gui.py", line 737, in buildChildrens
    dirs = os.listdir(currentPathFolder)

WindowsError: [Error 5] Acc�s refus: 'C:\\Documents and Settings\\*.*'

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          utf8' codec can't decode byte 0xe9 in position 6: invalid continuation byte

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              utf8' codec can't decode byte 0xe9 in position 6: invalid continuation byte


[2016-05-22 17:17:06] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "wms_gui.py", line 775, in WMSCoreListLocalFiles
    currentFolderObject["children"] = buildChildrens((index + 1), pathFolders)

  File "wms_gui.py", line 742, in buildChildrens
    'text': file.encode('latin-1'),

Unutf8' codec can't decode byte 0xe9 in position 6: invalid continuation byte

                                                                                                                                                                                                                                                                                                                                                                                                             utf8' codec can't decode byte 0xe9 in position 6: invalid continuation byte

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              utf8' codec can't decode byte 0xe9 in position 6: invalid continuation byte


[2016-05-22 17:17:06] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "wms_gui.py", line 775, in WMSCoreListLocalFiles
    currentFolderObject["children"] = buildChildrens((index + 1), pathFolders)

  File "wms_gui.py", line 742, in buildChildrens
    'text': file.encode('latin-1'),

Un
[2016-05-22 17:18:47] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "wms_gui.py", line 775, in WMSCoreListLocalFiles
    currentFolderObject["children"] = buildChildrens((index + 1), pathFolders)

  File "wms_gui.py", line 737, in buildChildrens
    dirs = os.listdir(currentPathFolder)

WindowsError: [Error 5] Acc�s refus: 'C:\\Documents and Settings\\*.*'


[2016-05-22 17:31:03] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File "wms_gui.py", line 784, in WMSCoreListLocalFiles
    currentFolderObject["children"] = buildChildrens((index + 1), pathFolders)

  File "wms_gui.py", line 740, in buildChildrens
    dirs = os.listdir(currentPathFolder)

WindowsError: [Error 5] Acc�s refus: 'C:\\Documents and Settings\\*.*'


[2016-05-23 11:37:55] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File ".\wms_gui.py", line 814, in WMSCoreStartLocalScan
    scandate = datetime.datetime.now()

NameError: global name 'datetime' is not defined


[2016-05-23 11:39:20] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File ".\wms_gui.py", line 818, in WMSCoreStartLocalScan
    self.WMSCoreUpdateScanResults()

  File ".\wms_gui.py", line 822, in WMSCoreUpdateScanResults
    rows = base64.b64encode(json.dumps(databaseCursor.fetchall()))

NameError: global name 'databaseCursor' is not defined


[2016-05-23 11:39:55] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File ".\wms_gui.py", line 819, in WMSCoreStartLocalScan
    self.WMSCoreUpdateScanResults()

  File ".\wms_gui.py", line 823, in WMSCoreUpdateScanResults
    rows = base64.b64encode(json.dumps(databaseCursor.fetchall()))

NameError: global name 'databaseCursor' is not defined


[2016-05-23 11:46:00] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File ".\wms_gui.py", line 826, in WMSCoreUpdateScanResults
    scan_id: row[0],

NameError: global name 'scan_id' is not defined


[2016-05-23 11:50:01] Traceback (most recent call last):

  File "load_handler_cef3.pyx", line 52, in cefpython_py27.LoadHandler_OnLoadEnd (cefpython.cpp:60218)

  File ".\wms_gui.py", line 624, in OnLoadEnd
    self.WMSLoad()

  File ".\wms_gui.py", line 655, in WMSLoad
    self.database = sqlite3.connect(self.databaseFile, row_factory=sqlite3.Row)

TypeError: 'row_factory' is an invalid keyword argument for this function


[2016-05-23 11:52:28] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File ".\wms_gui.py", line 828, in WMSCoreUpdateScanResults
    print rowstest[0].scan_id

AttributeError: 'sqlite3.Row' object has no attribute 'scan_id'


[2016-05-23 11:53:00] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File ".\wms_gui.py", line 828, in WMSCoreUpdateScanResults
    print rowstest[0]["scan_id"]

IndexError: No item with that key


[2016-05-23 11:55:28] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File ".\wms_gui.py", line 827, in WMSCoreUpdateScanResults
    rows = base64.b64encode(json.dumps(rows))

  File "c:\python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)

  File "c:\python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)

  File "c:\python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)

  File "c:\python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")

TypeError: <sqlite3.Row object at 0x023218D0> is not JSON serializable


[2016-05-23 12:17:08] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File ".\wms_gui.py", line 854, in WMSCoreNavigate
    self.browser.GetMainFrame().SetProperty('test', 'test123')

AttributeError: 'cefpython_py27.PyFrame' object has no attribute 'SetProperty'


[2016-05-23 12:31:54] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File ".\wms_gui.py", line 821, in WMSCoreStartLocalScan
    self.databaseCursor.execute("INSERT INTO scans(scandate, type, path, status) VALUES('"+scandate.strftime("%Y-%m-%d %H:%M:%S")+"','local','?','PENDING')", (str(LocalScanSelectedPath)))

ProgrammingError: Incorrect number of bindings supplied. The current statement uses 0, and there are 9 supplied.


[2016-05-23 12:34:00] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File ".\wms_gui.py", line 821, in WMSCoreStartLocalScan
    self.databaseCursor.execute("INSERT INTO scans(scandate, type, path, status) VALUES('"+scandate.strftime("%Y-%m-%d %H:%M:%S")+"','local','?','PENDING')", ('test'))

ProgrammingError: Incorrect number of bindings supplied. The current statement uses 0, and there are 4 supplied.


[2016-05-23 12:34:35] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File ".\wms_gui.py", line 821, in WMSCoreStartLocalScan
    self.databaseCursor.execute("INSERT INTO scans(scandate, type, path, status) VALUES('"+scandate.strftime("%Y-%m-%d %H:%M:%S")+"','local','?','PENDING')", 'test')

ProgrammingError: Incorrect number of bindings supplied. The current statement uses 0, and there are 4 supplied.


[2016-05-23 12:36:41] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

  File ".\wms_gui.py", line 821, in WMSCoreStartLocalScan
    self.databaseCursor.execute("INSERT INTO scans(scandate, type, path, status) VALUES('"+scandate.strftime("%Y-%m-%d %H:%M:%S")+"','local','?','PENDING')", [str(LocalScanSelectedPath)])

ProgrammingError: Incorrect number of bindings supplied. The current statement uses 0, and there are 1 supplied.


[2016-05-23 12:39:54] Traceback (most recent call last):

  File "v8function_handler_cef3.pyx", line 39, in cefpython_py27.V8FunctionHandler_Execute (cefpython.cpp:38833)

TypeError: WMSCoreStartRemoteScan() takes exactly 1 argument (6 given)


[2016-05-23 13:28:24] Traceback (most recent call last):

  File "load_handler_cef3.pyx", line 52, in cefpython_py27.LoadHandler_OnLoadEnd (cefpython.cpp:60218)

  File ".\wms_gui.py", line 658, in OnLoadEnd
    self.CreateScanTaskTimer()

  File ".\wms_gui.py", line 898, in CreateScanTaskTimer
    self.ScanTaskTimer = wx.Timer(self, self.ScanTaskTimerID)

AttributeError: 'WMSMainFrame' object has no attribute 'ScanTaskTimerID'


[2016-05-23 13:29:26] Traceback (most recent call last):

  File ".\wms_gui.py", line 905, in OnScanTaskTimer
    StartScanThread(row["id_scan"])

NameError: global name 'StartScanThread' is not defined


[2016-05-23 14:50:29] Traceback (most recent call last):

  File ".\wms_gui.py", line 930, in OnScanTaskTimer
    progress = SCANTHREADS[threadName].getProgress()

AttributeError: 'ScanThread' object has no attribute 'getProgress'

